### PR TITLE
Update version to v1.6.1

### PR DESCRIPTION
**Pull request by kapitoshka438**

### CODE REVIEW

**Review by tumarsal — APPROVED** [review]
LGFM

**Comment by happyalu** [comment]
How is this happening though? Shouldn't the tagged version match with the version in the documentation? I thought we had a script that verified this. maybe something changed. we should fix the process too.

**Comment by kapitoshka438** [comment]
> How is this happening though? Shouldn't the tagged version match with the version in the documentation? I thought we had a script that verified this. maybe something changed. we should fix the process too.
> 
> It's outlined here: https://github.com/cobaltspeech/sdk-cubic#tagging-new-versions

Do we still use this step for building docs locally with Hugo? I thought this is the purpose why we started using Render?

**Comment by kapitoshka438** [comment]
> > How is this happening though? Shouldn't the tagged version match with the version in the documentation? I thought we had a script that verified this. maybe something changed. we should fix the process too.
> > It's outlined here: https://github.com/cobaltspeech/sdk-cubic#tagging-new-versions
> 
> Do we still use this step for building docs locally with Hugo? I thought this is the purpose why we started using Render?

We've removed generated docs from the repo.

**Comment by renaissanceGeek** [comment]
> How is this happening though? Shouldn't the tagged version match with the version in the documentation? I thought we had a script that verified this. maybe something changed. we should fix the process too.
> 
> It's outlined here: https://github.com/cobaltspeech/sdk-cubic#tagging-new-versions

This PR does follow the steps you linked to, @happyalu, except as Eduard correctly points out, the hugo step is no longer necessary.  I just updated the README file to remove the obsolete reference to building the documentation.

**Review by renaissanceGeek — APPROVED** [review]
Looks like it needs to be rebased to pass Jenkins, but otherwise, I think it's good to go!

**Pull request merged**
